import { District } from "./types";

const districts: District[] = [
  { id: 99999, name: "Επικράτεια" },
  { id: 38, name: "Α Αθηνών" },
  { id: 60, name: "Β1 Βόρειου Τομέα Αθηνών" },
  { id: 61, name: "Β2 Δυτικού Τομέα Αθηνών" },
  { id: 62, name: "Β3 Νότιου Τομέα Αθηνών" },
  { id: 40, name: "Α Πειραιώς" },
  { id: 41, name: "Β Πειραιώς" },
  { id: 63, name: "Α Ανατολικής Αττικής" },
  { id: 64, name: "Β Δυτικής Αττικής" },
  { id: 30, name: "Αιτωλοακαρνανίας" },
  { id: 44, name: "Αργολίδος" },
  { id: 45, name: "Αρκαδίας" },
  { id: 19, name: "Άρτας" },
  { id: 31, name: "Αχαΐας" },
  { id: 36, name: "Βοιωτίας" },
  { id: 17, name: "Γρεβενών" },
  { id: 4, name: "Δράμας" },
  { id: 52, name: "Δωδεκανήσου" },
  { id: 1, name: "Έβρου" },
  { id: 37, name: "Ευβοίας" },
  { id: 34, name: "Ευρυτανίας" },
  { id: 29, name: "Ζακύνθου" },
  { id: 32, name: "Ηλείας" },
  { id: 12, name: "Ημαθίας" },
  { id: 55, name: "Ηρακλείου" },
  { id: 20, name: "Θεσπρωτίας" },
  { id: 6, name: "Α Θεσσαλονίκης" },
  { id: 7, name: "Β Θεσσαλονίκης" },
  { id: 18, name: "Ιωαννίνων" },
  { id: 5, name: "Καβάλας" },
  { id: 25, name: "Καρδίτσας" },
  { id: 16, name: "Καστοριάς" },
  { id: 26, name: "Κέρκυρας" },
  { id: 28, name: "Κεφαλληνίας" },
  { id: 10, name: "Κιλκίς" },
  { id: 15, name: "Κοζάνης" },
  { id: 43, name: "Κορινθίας" },
  { id: 51, name: "Κυκλάδων" },
  { id: 47, name: "Λακωνίας" },
  { id: 22, name: "Λάρισας" },
  { id: 56, name: "Λασιθίου" },
  { id: 48, name: "Λέσβου" },
  { id: 27, name: "Λευκάδας" },
  { id: 23, name: "Μαγνησίας" },
  { id: 46, name: "Μεσσηνίας" },
  { id: 3, name: "Ξάνθης" },
  { id: 11, name: "Πέλλας" },
  { id: 13, name: "Πιερίας" },
  { id: 21, name: "Πρέβεζας" },
  { id: 54, name: "Ρεθύμνης" },
  { id: 2, name: "Ροδόπης" },
  { id: 50, name: "Σάμου" },
  { id: 8, name: "Σερρών" },
  { id: 24, name: "Τρικάλων" },
  { id: 33, name: "Φθιώτιδας" },
  { id: 14, name: "Φλώρινας" },
  { id: 35, name: "Φωκίδας" },
  { id: 9, name: "Χαλκιδικής" },
  { id: 53, name: "Χανίων" },
  { id: 49, name: "Χίου" },
  { id: 57, name: "Εξωτερικού" },
];

export function getDistrictName(id: number): string | undefined {
  const district = districts.find((d) => d.id === id);
  return district ? district.name : 'Επικρατείας';
}
